# Generated by Django 5.0.2 on 2025-03-15 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_escolar_api', '0002_administradores_alumnos_maestros_delete_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='administradores',
            name='telefono',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
