# Generated by Django 5.0.2 on 2025-03-15 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_escolar_api', '0003_administradores_telefono'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maestros',
            old_name='fecha_nacimmiento',
            new_name='fecha_nacimiento',
        ),
    ]
