# Generated by Django 5.0.2 on 2025-05-17 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_escolar_api', '0004_rename_fecha_nacimmiento_maestros_fecha_nacimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_evento', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_realizacion', models.DateTimeField(blank=True, null=True)),
                ('horario', models.DateTimeField(blank=True, null=True)),
                ('lugar', models.CharField(blank=True, max_length=255, null=True)),
                ('publico_json', models.TextField(blank=True, null=True)),
                ('programa_educativo', models.CharField(blank=True, max_length=255, null=True)),
                ('responsable', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('cupo_maximo', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
