# Generated by Django 5.0.2 on 2025-05-18 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_escolar_api', '0005_eventos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventos',
            old_name='horario',
            new_name='hora_fin',
        ),
        migrations.AddField(
            model_name='eventos',
            name='hora_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
