# Generated by Django 5.0.2 on 2025-05-18 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_escolar_api', '0006_rename_horario_eventos_hora_fin_eventos_hora_inicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventos',
            name='hora_fin',
        ),
        migrations.AddField(
            model_name='eventos',
            name='hora_final',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='cupo_maximo',
            field=models.IntegerField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
