# Generated by Django 5.0.2 on 2025-05-18 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_escolar_api', '0007_remove_eventos_hora_fin_eventos_hora_final_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventos',
            old_name='hora_final',
            new_name='hora_fin',
        ),
    ]
