# Generated by Django 5.0.2 on 2025-05-18 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_escolar_api', '0008_rename_hora_final_eventos_hora_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='cupo_maximo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
