# Generated by Django 5.0.2 on 2025-05-19 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_escolar_api', '0011_alter_eventos_cupo_maximo_alter_eventos_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
